apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rbp-metrics-logger
spec:
  selector:
    matchLabels:
      app: rbp-metrics-logger
  template:
    metadata:
      labels:
        app: rbp-metrics-logger # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: rbp-metrics-logger
          image: lakshanbanneheke/rbp-metrics-logger:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: "/logs"
              name: log-files-pv-storage
      volumes:
        - name: log-files-pv-storage
          persistentVolumeClaim:
            claimName: log-files-pv-claim